# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='neighbour.Neighbourhoods'),
            preserve_default=False,
        ),
    ]
