# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Hotline', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='neighbourhoods',
            name='details',
        ),
        migrations.AddField(
            model_name='businesses',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='neighbour.Neighbourhoods'),
        ),
        migrations.AddField(
            model_name='neighbourhoods',
            name='hotlines',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='neigbourhoods', to='neighbour.Hotlines'),
            preserve_default=False,
        ),
    ]
