# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_auto_20181019_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhoods',
            name='health',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbourhoods',
            name='hotlines',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Hotlines',
        ),
    ]
