# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbour', '0005_neighbourhoods_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhoods',
            name='user',
        ),
        migrations.AddField(
            model_name='neighbourhoods',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
