# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0006_auto_20181022_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='neighbour.Neighbourhoods'),
        ),
    ]
