# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbour', '0007_auto_20181022_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhoods',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
