# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0007_neighbourhoods_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('no', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='neighbourhoods',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='neighbourhoods',
            name='health',
        ),
        migrations.RemoveField(
            model_name='neighbourhoods',
            name='hotlines',
        ),
        migrations.AddField(
            model_name='neighbourhoods',
            name='hotline',
            field=models.ManyToManyField(related_name='hotline', to='neighbour.Hotline'),
        ),
    ]
