# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0008_auto_20181019_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhoods',
            name='hotline',
        ),
        migrations.AddField(
            model_name='neighbourhoods',
            name='hotline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotline', to='neighbour.Hotline'),
            preserve_default=False,
        ),
    ]
