# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0009_auto_20181019_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhoods',
            name='hotline',
        ),
    ]
